/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignupIndexRouteImport } from './routes/_public/signup/index'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedGunplaKitsKitsIndexRouteImport } from './routes/_authenticated/gunpla-kits/kits/index'
import { Route as AuthenticatedGunplaKitsKitsNewRouteImport } from './routes/_authenticated/gunpla-kits/kits/new'
import { Route as AuthenticatedGunplaKitsKitsColorsIndexRouteImport } from './routes/_authenticated/gunpla-kits/kits/colors/index'
import { Route as AuthenticatedGunplaKitsKitsKitIdIndexRouteImport } from './routes/_authenticated/gunpla-kits/kits/$kitId/index'
import { Route as AuthenticatedGunplaKitsKitsColorsNewRouteImport } from './routes/_authenticated/gunpla-kits/kits/colors/new'
import { Route as AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRouteImport } from './routes/_authenticated/gunpla-kits/kits/$kitId/runners/$runner'
import { Route as AuthenticatedGunplaKitsKitsKitIdPartNewRouteImport } from './routes/_authenticated/gunpla-kits/kits/$kitId/part/new'
import { Route as AuthenticatedGunplaKitsKitsKitIdPartPartIdRouteImport } from './routes/_authenticated/gunpla-kits/kits/$kitId/part/$partId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignupIndexRoute = PublicSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGunplaKitsKitsIndexRoute =
  AuthenticatedGunplaKitsKitsIndexRouteImport.update({
    id: '/gunpla-kits/kits/',
    path: '/gunpla-kits/kits/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGunplaKitsKitsNewRoute =
  AuthenticatedGunplaKitsKitsNewRouteImport.update({
    id: '/gunpla-kits/kits/new',
    path: '/gunpla-kits/kits/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGunplaKitsKitsColorsIndexRoute =
  AuthenticatedGunplaKitsKitsColorsIndexRouteImport.update({
    id: '/gunpla-kits/kits/colors/',
    path: '/gunpla-kits/kits/colors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGunplaKitsKitsKitIdIndexRoute =
  AuthenticatedGunplaKitsKitsKitIdIndexRouteImport.update({
    id: '/gunpla-kits/kits/$kitId/',
    path: '/gunpla-kits/kits/$kitId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGunplaKitsKitsColorsNewRoute =
  AuthenticatedGunplaKitsKitsColorsNewRouteImport.update({
    id: '/gunpla-kits/kits/colors/new',
    path: '/gunpla-kits/kits/colors/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRoute =
  AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRouteImport.update({
    id: '/gunpla-kits/kits/$kitId/runners/$runner',
    path: '/gunpla-kits/kits/$kitId/runners/$runner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGunplaKitsKitsKitIdPartNewRoute =
  AuthenticatedGunplaKitsKitsKitIdPartNewRouteImport.update({
    id: '/gunpla-kits/kits/$kitId/part/new',
    path: '/gunpla-kits/kits/$kitId/part/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGunplaKitsKitsKitIdPartPartIdRoute =
  AuthenticatedGunplaKitsKitsKitIdPartPartIdRouteImport.update({
    id: '/gunpla-kits/kits/$kitId/part/$partId',
    path: '/gunpla-kits/kits/$kitId/part/$partId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/signup': typeof PublicSignupIndexRoute
  '/gunpla-kits/kits/new': typeof AuthenticatedGunplaKitsKitsNewRoute
  '/gunpla-kits/kits': typeof AuthenticatedGunplaKitsKitsIndexRoute
  '/gunpla-kits/kits/colors/new': typeof AuthenticatedGunplaKitsKitsColorsNewRoute
  '/gunpla-kits/kits/$kitId': typeof AuthenticatedGunplaKitsKitsKitIdIndexRoute
  '/gunpla-kits/kits/colors': typeof AuthenticatedGunplaKitsKitsColorsIndexRoute
  '/gunpla-kits/kits/$kitId/part/$partId': typeof AuthenticatedGunplaKitsKitsKitIdPartPartIdRoute
  '/gunpla-kits/kits/$kitId/part/new': typeof AuthenticatedGunplaKitsKitsKitIdPartNewRoute
  '/gunpla-kits/kits/$kitId/runners/$runner': typeof AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/signup': typeof PublicSignupIndexRoute
  '/gunpla-kits/kits/new': typeof AuthenticatedGunplaKitsKitsNewRoute
  '/gunpla-kits/kits': typeof AuthenticatedGunplaKitsKitsIndexRoute
  '/gunpla-kits/kits/colors/new': typeof AuthenticatedGunplaKitsKitsColorsNewRoute
  '/gunpla-kits/kits/$kitId': typeof AuthenticatedGunplaKitsKitsKitIdIndexRoute
  '/gunpla-kits/kits/colors': typeof AuthenticatedGunplaKitsKitsColorsIndexRoute
  '/gunpla-kits/kits/$kitId/part/$partId': typeof AuthenticatedGunplaKitsKitsKitIdPartPartIdRoute
  '/gunpla-kits/kits/$kitId/part/new': typeof AuthenticatedGunplaKitsKitsKitIdPartNewRoute
  '/gunpla-kits/kits/$kitId/runners/$runner': typeof AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/signup/': typeof PublicSignupIndexRoute
  '/_authenticated/gunpla-kits/kits/new': typeof AuthenticatedGunplaKitsKitsNewRoute
  '/_authenticated/gunpla-kits/kits/': typeof AuthenticatedGunplaKitsKitsIndexRoute
  '/_authenticated/gunpla-kits/kits/colors/new': typeof AuthenticatedGunplaKitsKitsColorsNewRoute
  '/_authenticated/gunpla-kits/kits/$kitId/': typeof AuthenticatedGunplaKitsKitsKitIdIndexRoute
  '/_authenticated/gunpla-kits/kits/colors/': typeof AuthenticatedGunplaKitsKitsColorsIndexRoute
  '/_authenticated/gunpla-kits/kits/$kitId/part/$partId': typeof AuthenticatedGunplaKitsKitsKitIdPartPartIdRoute
  '/_authenticated/gunpla-kits/kits/$kitId/part/new': typeof AuthenticatedGunplaKitsKitsKitIdPartNewRoute
  '/_authenticated/gunpla-kits/kits/$kitId/runners/$runner': typeof AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/login'
    | '/signup'
    | '/gunpla-kits/kits/new'
    | '/gunpla-kits/kits'
    | '/gunpla-kits/kits/colors/new'
    | '/gunpla-kits/kits/$kitId'
    | '/gunpla-kits/kits/colors'
    | '/gunpla-kits/kits/$kitId/part/$partId'
    | '/gunpla-kits/kits/$kitId/part/new'
    | '/gunpla-kits/kits/$kitId/runners/$runner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/login'
    | '/signup'
    | '/gunpla-kits/kits/new'
    | '/gunpla-kits/kits'
    | '/gunpla-kits/kits/colors/new'
    | '/gunpla-kits/kits/$kitId'
    | '/gunpla-kits/kits/colors'
    | '/gunpla-kits/kits/$kitId/part/$partId'
    | '/gunpla-kits/kits/$kitId/part/new'
    | '/gunpla-kits/kits/$kitId/runners/$runner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/apps/'
    | '/_public/login/'
    | '/_public/signup/'
    | '/_authenticated/gunpla-kits/kits/new'
    | '/_authenticated/gunpla-kits/kits/'
    | '/_authenticated/gunpla-kits/kits/colors/new'
    | '/_authenticated/gunpla-kits/kits/$kitId/'
    | '/_authenticated/gunpla-kits/kits/colors/'
    | '/_authenticated/gunpla-kits/kits/$kitId/part/$partId'
    | '/_authenticated/gunpla-kits/kits/$kitId/part/new'
    | '/_authenticated/gunpla-kits/kits/$kitId/runners/$runner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signup/': {
      id: '/_public/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gunpla-kits/kits/': {
      id: '/_authenticated/gunpla-kits/kits/'
      path: '/gunpla-kits/kits'
      fullPath: '/gunpla-kits/kits'
      preLoaderRoute: typeof AuthenticatedGunplaKitsKitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gunpla-kits/kits/new': {
      id: '/_authenticated/gunpla-kits/kits/new'
      path: '/gunpla-kits/kits/new'
      fullPath: '/gunpla-kits/kits/new'
      preLoaderRoute: typeof AuthenticatedGunplaKitsKitsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gunpla-kits/kits/colors/': {
      id: '/_authenticated/gunpla-kits/kits/colors/'
      path: '/gunpla-kits/kits/colors'
      fullPath: '/gunpla-kits/kits/colors'
      preLoaderRoute: typeof AuthenticatedGunplaKitsKitsColorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gunpla-kits/kits/$kitId/': {
      id: '/_authenticated/gunpla-kits/kits/$kitId/'
      path: '/gunpla-kits/kits/$kitId'
      fullPath: '/gunpla-kits/kits/$kitId'
      preLoaderRoute: typeof AuthenticatedGunplaKitsKitsKitIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gunpla-kits/kits/colors/new': {
      id: '/_authenticated/gunpla-kits/kits/colors/new'
      path: '/gunpla-kits/kits/colors/new'
      fullPath: '/gunpla-kits/kits/colors/new'
      preLoaderRoute: typeof AuthenticatedGunplaKitsKitsColorsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gunpla-kits/kits/$kitId/runners/$runner': {
      id: '/_authenticated/gunpla-kits/kits/$kitId/runners/$runner'
      path: '/gunpla-kits/kits/$kitId/runners/$runner'
      fullPath: '/gunpla-kits/kits/$kitId/runners/$runner'
      preLoaderRoute: typeof AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gunpla-kits/kits/$kitId/part/new': {
      id: '/_authenticated/gunpla-kits/kits/$kitId/part/new'
      path: '/gunpla-kits/kits/$kitId/part/new'
      fullPath: '/gunpla-kits/kits/$kitId/part/new'
      preLoaderRoute: typeof AuthenticatedGunplaKitsKitsKitIdPartNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gunpla-kits/kits/$kitId/part/$partId': {
      id: '/_authenticated/gunpla-kits/kits/$kitId/part/$partId'
      path: '/gunpla-kits/kits/$kitId/part/$partId'
      fullPath: '/gunpla-kits/kits/$kitId/part/$partId'
      preLoaderRoute: typeof AuthenticatedGunplaKitsKitsKitIdPartPartIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedGunplaKitsKitsNewRoute: typeof AuthenticatedGunplaKitsKitsNewRoute
  AuthenticatedGunplaKitsKitsIndexRoute: typeof AuthenticatedGunplaKitsKitsIndexRoute
  AuthenticatedGunplaKitsKitsColorsNewRoute: typeof AuthenticatedGunplaKitsKitsColorsNewRoute
  AuthenticatedGunplaKitsKitsKitIdIndexRoute: typeof AuthenticatedGunplaKitsKitsKitIdIndexRoute
  AuthenticatedGunplaKitsKitsColorsIndexRoute: typeof AuthenticatedGunplaKitsKitsColorsIndexRoute
  AuthenticatedGunplaKitsKitsKitIdPartPartIdRoute: typeof AuthenticatedGunplaKitsKitsKitIdPartPartIdRoute
  AuthenticatedGunplaKitsKitsKitIdPartNewRoute: typeof AuthenticatedGunplaKitsKitsKitIdPartNewRoute
  AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRoute: typeof AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedGunplaKitsKitsNewRoute: AuthenticatedGunplaKitsKitsNewRoute,
  AuthenticatedGunplaKitsKitsIndexRoute: AuthenticatedGunplaKitsKitsIndexRoute,
  AuthenticatedGunplaKitsKitsColorsNewRoute:
    AuthenticatedGunplaKitsKitsColorsNewRoute,
  AuthenticatedGunplaKitsKitsKitIdIndexRoute:
    AuthenticatedGunplaKitsKitsKitIdIndexRoute,
  AuthenticatedGunplaKitsKitsColorsIndexRoute:
    AuthenticatedGunplaKitsKitsColorsIndexRoute,
  AuthenticatedGunplaKitsKitsKitIdPartPartIdRoute:
    AuthenticatedGunplaKitsKitsKitIdPartPartIdRoute,
  AuthenticatedGunplaKitsKitsKitIdPartNewRoute:
    AuthenticatedGunplaKitsKitsKitIdPartNewRoute,
  AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRoute:
    AuthenticatedGunplaKitsKitsKitIdRunnersRunnerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicSignupIndexRoute: typeof PublicSignupIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicSignupIndexRoute: PublicSignupIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
